{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cpuUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "requestLatency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(orderLatency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(requestsByMethod_total{source=\"jwt-pizza-service\", method!=\"OPTIONS\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Current active users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "Recent active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active users"
    }
   ]
  },
  {
   "title": "Authentication attempts per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "rate(loginSuccessCount_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Login success"
    },
    {
     "expr": "rate(loginFailureCount_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Login failure"
    }
   ]
  },
  {
   "title": "Revenue per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "₿" } },
   "targets": [
    {
     "expr": "rate(totalRevenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Total revenue last period",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "₿" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(totalRevenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizzas sold per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(pizzasSold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizzas sold"
    }
   ]
  },
  {
   "title": "Purchases per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "rate(orderSuccessCount_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase success"
    },
    {
     "expr": "rate(orderFailureCount_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Purchase failure"
    }
   ]
  }
 ]
}